version: '3'
services:
  power-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-power-api
    volumes:
      - ./vlab_power_api:/usr/lib/python3.6/site-packages/vlab_power_api
    command: ["python3", "app.py"]

  power-worker:
    image:
      willnx/vlab-power-worker
    volumes:
      - ./vlab_power_api:/usr/lib/python3.6/site-packages/vlab_power_api

  power-broker:
    image:
      rabbitmq:3.7-alpine
