version: '3'
services:
  power-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-power-api
    volumes:
      - ./vlab_power_api:/usr/lib/python3.6/site-packages/vlab_power_api
    command: ["python3", "app.py"]

  power-worker:
    image:
      willnx/vlab-power-worker
    volumes:
      - ./vlab_power_api:/usr/lib/python3.6/site-packages/vlab_power_api
    environment:
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  power-broker:
    image:
      rabbitmq:3.7-alpine
